name: Bug Report
description: File a bug report
title: "[Bug]: Brief Description of bug here"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! please fill out as much of this as you can.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Description of the bug:"
    validations:
      required: true
  - type: input
    id: discord
    attributes:
      label: Discord Username
      description: Please enter your discord username incase we need more info. Other forms of contact info are valid, but discord is perfered.
      placeholder: ex. Kono Tyran#1865
    validations:
      required: false
  - type: checkboxes
    id: apworldtype
    attributes:
      label: Apworld type
      description: What apworld was used?
      options:
        - label: Main
        - label: Dig
    validations:
      required: true
  - type: input
    id: apworldversiongen
    attributes:
      label: Apworld generation version
      description: What version was this generated happen on?
    validations:
      required: true
  - type: input
    id: archipelagoversiongen
    attributes:
      label: Archipelago generation version
      description: What Archipelago Launcher version did this get generated happen on?
    validations:
      required: true
  - type: input
    id: apworldversion
    attributes:
      label: Apworld version
      description: What version for the client did this happen on?
    validations:
      required: true
  - type: input
    id: archipelagoversion
    attributes:
      label: Archipelago version
      description: What Archipelago Launcher version did this happen on?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Where did this error take place?
      options:
        - Archipelago Minecraft Client
        - Minecraft Server
        - Minecraft
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
